// Stamps every same-origin file a page loads with a hash of its content, so that a changed file has a new address
// and an old copy can never be served for it. No version is bumped by hand any more.
//
//   node scripts/stamp.mjs           rewrite the stamps (the pre-commit hook runs this)
//   node scripts/stamp.mjs --check   change nothing; exit 1 and list the files whose stamps are stale
//
// What it does:
//   1. hashes (sha256, first 10 hex) the scripts and styles the three pages load, the vendored d3, and the data files
//      (data/*.json and data/data_<lang>.js);
//   2. writes data/version.js, the map the page scripts use to ask for data as file?v=<hash>;
//   3. rewrites the references in index.html, tree/index.html and more/index.html to file?v=<hash>, and makes sure each
//      page loads data/version.js before its other scripts;
//   4. rewrites the precache list in sw.js the same way, and sets CACHE_NAME from all the hashes.
// Running it twice changes nothing.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const root = path.resolve(new URL('../', import.meta.url).pathname);
const check = process.argv.includes('--check');
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');
const exists = (p) => fs.existsSync(path.join(root, p));
const hash = (text) => crypto.createHash('sha256').update(text).digest('hex').slice(0, 10);
const hashFile = (p) => hash(fs.readFileSync(path.join(root, p)));

const PAGES = ['index.html', 'tree/index.html', 'more/index.html'];
const VERSION_FILE = 'data/version.js';
const REF = /(\b(?:src|href)=")([^"?#]+\.(?:js|css))(?:\?v=[0-9a-f]+)?(")/g;

// a reference in a page → the file's path from the repo root (null for another site, or a root-absolute address)
function resolve(page, html, ref) {
  if (/^(?:[a-z]+:)?\/\//i.test(ref) || ref.startsWith('/')) return null;
  const base = /<base href="\.\.\/">/.test(html) ? path.posix.dirname(path.posix.dirname(page)) : path.posix.dirname(page);
  const p = path.posix.normalize(path.posix.join(base === '.' ? '' : base, ref));
  return p.startsWith('..') ? null : p;
}

/* 1. the files to stamp: what the pages reference, and the data */
const pages = Object.fromEntries(PAGES.map((p) => [p, read(p)]));
const files = new Set();
for (const [page, html] of Object.entries(pages)) for (const m of html.matchAll(REF)) { const p = resolve(page, html, m[2]); if (p && p !== VERSION_FILE && exists(p)) files.add(p); }
const data = fs.readdirSync(path.join(root, 'data')).filter((f) => /\.json$/.test(f) || /^data_[a-z]+\.js$/.test(f)).map((f) => `data/${f}`).sort();
data.forEach((p) => files.add(p));
const hashes = Object.fromEntries([...files].sort().map((p) => [p, hashFile(p)]));

/* 2. data/version.js: the map for the data the scripts fetch */
const versionJs = `/* Generated by scripts/stamp.mjs — do not edit. The content hash of each data file: the page scripts ask for
   data as file?v=<hash>, so a changed file has a new address and an old copy is never used for it. */
window.SITE_V = ${JSON.stringify(Object.fromEntries(data.map((p) => [p, hashes[p]])), null, 1)};
`;
hashes[VERSION_FILE] = hash(versionJs);

/* 3. the pages */
const out = { [VERSION_FILE]: versionJs };
for (const [page, html] of Object.entries(pages)) {
  let h = html;
  // every page loads the version map before its other scripts (right after theme.js, in <head>)
  if (!/data\/version\.js/.test(h)) {
    const theme = /^([ \t]*)<script src="((?:\.\.\/)?)theme\.js(?:\?v=[0-9a-f]+)?"><\/script>\n/m.exec(h);
    if (!theme) throw new Error(`${page}: no theme.js script to put data/version.js after`);
    h = h.replace(theme[0], `${theme[0]}${theme[1]}<script src="${theme[2]}data/version.js"></script>\n`);
  }
  h = h.replace(REF, (all, pre, ref, post) => { const p = resolve(page, h, ref); return p && hashes[p] ? `${pre}${ref}?v=${hashes[p]}${post}` : all; });
  out[page] = h;
}

/* 4. the service worker: its precache list, and a cache name made from every hash and every page */
let sw = read('sw.js');
sw = sw.replace(/'\.\/([^'?]+\.(?:js|css|json))(?:\?v=[0-9a-f]+)?'/g, (all, p) => (hashes[p] ? `'./${p}?v=${hashes[p]}'` : all));
const all = hash(Object.keys(hashes).sort().map((p) => `${p}:${hashes[p]}`).join('\n') + '\n' + PAGES.map((p) => `${p}:${hash(out[p])}`).join('\n'));
if (!/const CACHE_NAME = '[^']*';/.test(sw)) throw new Error('sw.js: CACHE_NAME not found');
sw = sw.replace(/const CACHE_NAME = '[^']*';/, `const CACHE_NAME = 'jamalibnadam-${all}';`);
out['sw.js'] = sw;

/* write, or report */
const stale = Object.keys(out).filter((p) => !exists(p) || read(p) !== out[p]);
if (check) {
  if (stale.length) { console.error(`stamp: stale — run "node scripts/stamp.mjs" (${stale.join(', ')})`); process.exit(1); }
  console.log(`stamp: up to date (${Object.keys(hashes).length} files, cache jamalibnadam-${all})`);
} else {
  stale.forEach((p) => fs.writeFileSync(path.join(root, p), out[p]));
  console.log(stale.length ? `stamp: updated ${stale.join(', ')} (cache jamalibnadam-${all})` : `stamp: nothing to change (cache jamalibnadam-${all})`);
}
